void initBoard();
void printBoard(int);
void userInput(int);
int knight(int, int);
int pawn(int, int, int);
int rook(int, int);
int bishop(int, int);
int queen(int, int);
int king(int, int);
int calcCheck(int);
int bishopCheck();
int rookCheck();
int queenCheck();
int pawnCheck();
int kingCheck();
int knightCheck();
void pawnPromotion();
int calcCheckmate(int);
int pawnCm(int, int, int);
