void initBoard(int[]);
void printBoard(int[], int);
void userInput(int[], int);
int knight(int, int);
int pawn(int[], int, int, int);
int rook(int[], int, int);
int bishop(int[], int, int);
int queen(int[], int, int);
int king(int[], int, int);
int calcCheck(int[], int);
int bishopCheck(int[]);
int rookCheck(int[]);
int queenCheck(int[]);
int pawnCheck(int[], int);
